# Generated by Django 4.1.4 on 2023-01-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_section_slides_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slides',
            old_name='slide',
            new_name='slider',
        ),
    ]
