# Generated by Django 4.1.4 on 2023-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_slide_slides_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slides',
            name='desc_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slides',
            name='desc_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
