# Generated by Django 4.1.4 on 2023-01-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_slider_name_alter_slides_desc_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='slides',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', max_length=10),
        ),
    ]
