# Generated by Django 4.1.4 on 2023-01-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_section_text_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='slides',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=10),
        ),
    ]
