# Generated by Django 4.1.4 on 2023-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_section_text_align_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_tag_manager_body_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='google_tag_manager_header_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
