# Generated by Django 4.1.5 on 2023-01-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_setting_google_tag_manager_body_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='google_tag_manager_body_key',
            new_name='google_tag_manager_key',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='google_tag_manager_header_key',
        ),
    ]
