# Generated by Django 4.1.5 on 2023-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_page_meta_description_page_meta_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
