# Generated by Django 4.1.4 on 2022-12-19 04:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='homepage_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Homepage Logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_address',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
