# Generated by Django 4.1.4 on 2022-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_setting_homepage_logo_alter_setting_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='homepage_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
