# Generated by Django 4.1.4 on 2022-12-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_setting_footer_logo_alter_setting_homepage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_logo',
            field=models.FileField(blank=True, null=True, upload_to='Footer Logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='homepage_logo',
            field=models.FileField(blank=True, null=True, upload_to='Homepage Logo'),
        ),
    ]
