# Generated by Django 4.1.4 on 2022-12-26 05:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_section_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='background_color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
