# Generated by Django 4.1.4 on 2022-12-26 06:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_section_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
