# Generated by Django 4.1.3 on 2022-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='excerpt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
