# Generated by Django 4.1.4 on 2022-12-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_setting_homepage_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='service_image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
