# Generated by Django 4.1.3 on 2022-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_title_service_name_service_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
