# Generated by Django 4.1.3 on 2022-11-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_serviceoffering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='service',
            table='gender',
        ),
    ]
