# Generated by Django 4.1.3 on 2022-11-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_service_options_alter_service_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
