# Generated by Django 4.1.4 on 2022-12-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_setting_footer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.page'),
            preserve_default=False,
        ),
    ]
