# Generated by Django 4.1.4 on 2022-12-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_section_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.page'),
        ),
    ]
