# Generated by Django 4.1.3 on 2022-11-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_service_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceoffering',
            table='service_offering',
        ),
    ]
