# Generated by Django 4.1.3 on 2022-11-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_serviceoffering_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
