# Generated by Django 4.1.4 on 2022-12-20 05:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_section_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='common_service_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
