# Generated by Django 4.1.3 on 2022-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_service_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
