# Generated by Django 4.1.3 on 2022-12-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_queryform_email_as_send"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="is_flag",
            new_name="is_featured",
        ),
    ]
