# Generated by Django 4.1.3 on 2022-12-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0012_rename_is_flag_service_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="description",
        ),
    ]
