# Generated by Django 4.1.3 on 2022-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_remove_page_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsection",
            old_name="section_icon",
            new_name="icon",
        ),
        migrations.AlterField(
            model_name="page",
            name="header_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Header Image",
                verbose_name="Header Image",
            ),
        ),
    ]
