# Generated by Django 4.1.3 on 2022-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
