# Generated by Django 4.1.3 on 2022-11-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
