# Generated by Django 4.1.3 on 2022-12-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0015_rename_image_serviceoffering_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="service_image",
            new_name="image",
        ),
    ]
