# Generated by Django 4.1.4 on 2022-12-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_rename_service_image_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='HeaderImage', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='FooterLogo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='homepage_logo',
            field=models.ImageField(blank=True, null=True, upload_to='HomepageLogo'),
        ),
    ]
