# Generated by Django 4.1.3 on 2022-11-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='serviceoffering',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
