# Generated by Django 4.1.4 on 2022-12-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_page_sequence_alter_page_header_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sequence',
        ),
        migrations.AddField(
            model_name='menu',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
