# Generated by Django 4.1.3 on 2022-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_service_options_alter_serviceoffering_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='section_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='serviceoffering',
            options={'ordering': ['created_on']},
        ),
    ]
