# Generated by Django 4.1.4 on 2022-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_page_sequence_menu_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_mail_us_button',
            field=models.BooleanField(default=False, verbose_name='Show Mail Us Button'),
        ),
    ]
