# Generated by Django 4.1.3 on 2022-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_section_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='section',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
