# Generated by Django 4.1.3 on 2022-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_section_options_section_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
