# Generated by Django 4.1.3 on 2022-11-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_section_text_align_subsection_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text_align',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0),
        ),
    ]
