# Generated by Django 4.1.4 on 2022-12-26 05:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_section_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
