# Generated by Django 4.1.3 on 2022-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_section_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default=0, max_length=10),
        ),
    ]
