# Generated by Django 4.1.3 on 2022-11-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_alter_section_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('other', 'Other')], default=0, max_length=10),
        ),
    ]
