# Generated by Django 4.1.3 on 2022-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('other', 'Other'), ('owner', 'Owner')], default=0, max_length=10),
        ),
    ]
