# Generated by Django 4.1.3 on 2022-11-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='section_icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons'),
        ),
    ]
