# Generated by Django 4.1.3 on 2022-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0029_serviceoffering_updated_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subsection",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(null=True, upload_to="Section"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="Service"),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="image",
            field=models.ImageField(upload_to="ServiceOffering"),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="section_icon",
            field=models.ImageField(blank=True, null=True, upload_to="SubSection"),
        ),
    ]
