# Generated by Django 4.1.3 on 2022-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_section_updated_on_service_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='subsection',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('other', 'Other'), ('owner', 'Owner')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
    ]
