# Generated by Django 4.1.3 on 2022-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_section_status_service_status_serviceoffering_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
    ]
