# Generated by Django 4.1.3 on 2022-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
