# Generated by Django 4.1.3 on 2022-11-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_alter_menu_image_alter_menu_name_alter_menu_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='slug',
            new_name='menu_slug',
        ),
    ]
