# Generated by Django 4.1.3 on 2022-11-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_rename_slug_menu_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_slug',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.service'),
        ),
    ]
