# Generated by Django 4.1.3 on 2022-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_remove_menu_menu_slug_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('service', 'Service')], max_length=10, null=True),
        ),
    ]
