# Generated by Django 4.1.3 on 2022-11-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug_type',
        ),
        migrations.AddField(
            model_name='menu',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.service'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
