# Generated by Django 4.1.3 on 2022-11-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_remove_service_slug_type_menu_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='Header Image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.service')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['created_on'],
            },
        ),
    ]
