# Generated by Django 4.1.3 on 2022-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
