# Generated by Django 4.1.3 on 2022-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0042_service_is_flag_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Service'),
        ),
    ]
