# Generated by Django 4.1.3 on 2022-12-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='service',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='setting',
            table='auth_user',
        ),
    ]
