# Generated by Django 4.1.3 on 2022-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0048_remove_page_service_page_content_page_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
