# Generated by Django 4.1.3 on 2022-12-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0049_alter_page_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
    ]
