# Generated by Django 4.1.3 on 2022-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_remove_page_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
