# Generated by Django 4.1.3 on 2022-12-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0051_alter_service_excerpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
