# Generated by Django 4.1.3 on 2022-12-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0053_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
