# Generated by Django 4.1.3 on 2022-12-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0054_remove_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('other', 'Other'), ('owner', 'Owner'), ('canada_jetline', 'Canada Jetline Cargo')], default='other', max_length=20),
        ),
    ]
