# Generated by Django 4.1.3 on 2022-12-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0056_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='background_image',
        ),
    ]
