# Generated by Django 4.1.3 on 2022-12-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0057_remove_footer_background_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='QueryForm',
        ),
        migrations.AlterModelTable(
            name='queryform',
            table='query_form',
        ),
    ]
