# Generated by Django 4.1.3 on 2022-12-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0058_rename_contact_queryform_alter_queryform_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='show_on_about_page',
            field=models.BooleanField(default=False),
        ),
    ]
