# Generated by Django 4.1.3 on 2022-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0060_alter_section_section_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
