# Generated by Django 4.1.3 on 2022-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10),
        ),
    ]
